name: 'jds'
description: >
  编译 Jekyll 成 html 文件，可以配合 SFTP action 上传到相应的 NGINX 主机上面
inputs:
  provider:
    description: 'The deploy provider'
    required: true
  token:
    description: 'The deploy token'
    required: false
  repository:
    description: 'The deploy repository'
    required: false
  branch:
    description: 'The deploy branch'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  cname:
    description: 'The cname to use for the site'
    required: false
  bundler_ver:
    description: 'The Bundler version'
    required: false
  jekyll_src:
    description: 'The Jekyll website source directory'
    required: false
  jekyll_cfg:
    description: 'The Jekyll website config files'
    required: false
  jekyll_baseurl:
    description: 'The Jekyll website baseurl'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'command'
  color: 'red'